# Generated by Django 4.2.17 on 2025-12-16 01:14

from django.db import migrations, models
import django_summernote.fields
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('title', models.CharField(max_length=100, verbose_name='Ünvan')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
            },
        ),
        migrations.CreateModel(
            name='CommentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.CharField(max_length=100, verbose_name='Açıklama')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu Alanı',
                'verbose_name_plural': 'Müşteri Yorumu Alanı',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E Posta')),
                ('phone', models.CharField(max_length=254, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=254, verbose_name='Konu')),
                ('message', models.TextField(blank=True, verbose_name='Açıklama')),
                ('isRead', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Formu',
                'verbose_name_plural': 'İletişim Formu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sayaç Adı')),
                ('count', models.CharField(max_length=10, verbose_name='Sayaç Değeri')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome ikon adı (örn: fas fa-info)', max_length=50, verbose_name='Sayaç İkonu')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sayaç',
                'verbose_name_plural': 'Sayaçlar',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('showIndex', models.BooleanField(default=True, verbose_name='Anasayfa da gösterilsin mi?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'Sıkça Sorulan Sorular',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome ikon adı (örn: fas fa-info)', max_length=50, verbose_name='İcon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
            },
        ),
        migrations.CreateModel(
            name='Page_Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('page_url', models.CharField(max_length=100, verbose_name='Sayfa Url')),
            ],
            options={
                'verbose_name': 'SEO Ayarı',
                'verbose_name_plural': 'SEO Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('location', models.CharField(help_text='Örn: Kadıköy, İstanbul', max_length=100, verbose_name='Konum')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to='uploads/projects', verbose_name='Ana Görsel')),
                ('before_image', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Öncesi Görseli')),
                ('after_image', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Sonrası Görseli')),
                ('category', models.CharField(help_text='Örn: Mobilya Boyama', max_length=100, verbose_name='Kategori')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('show_on_index', models.BooleanField(default=True, verbose_name='Anasayfada Göster')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-is_featured', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Şirket Adı')),
                ('domain', models.CharField(blank=True, max_length=100, verbose_name='Domain Adresi')),
                ('logo', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='uploads', verbose_name='Logo')),
                ('logowhite', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='uploads', verbose_name='Logo(Beyaz Yüzey)')),
                ('favicon', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='uploads', verbose_name='Favicon')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='Whatsapp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E Posta')),
                ('adress', models.TextField(blank=True, verbose_name='Adres')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('alternate_name', models.CharField(blank=True, default='İFİ Yazılım Dijital Pazarlama', max_length=200, verbose_name='Alternatif İsim')),
                ('city', models.CharField(blank=True, default='İstanbul', max_length=100, verbose_name='Şehir')),
                ('region', models.CharField(blank=True, default='İstanbul', max_length=100, verbose_name='Bölge')),
                ('postal_code', models.CharField(blank=True, default='34000', max_length=20, verbose_name='Posta Kodu')),
                ('country', models.CharField(blank=True, default='TR', max_length=10, verbose_name='Ülke Kodu')),
                ('latitude', models.CharField(blank=True, default='41.0082', max_length=20, verbose_name='Enlem')),
                ('longitude', models.CharField(blank=True, default='28.9784', max_length=20, verbose_name='Boylam')),
                ('opening_hours', models.JSONField(blank=True, default=list, help_text='JSON formatında çalışma saatleri (örn: ["Mo-Fr 09:00-18:00"])', verbose_name='Çalışma Saatleri')),
                ('price_range', models.CharField(blank=True, default='$$', max_length=10, verbose_name='Fiyat Aralığı')),
                ('payment_accepted', models.CharField(blank=True, default='Cash, Credit Card, Bank Transfer', max_length=200, verbose_name='Kabul Edilen Ödeme Yöntemleri')),
                ('currencies_accepted', models.CharField(blank=True, default='TRY, USD, EUR', max_length=50, verbose_name='Kabul Edilen Para Birimleri')),
                ('founding_date', models.CharField(blank=True, default='2021', max_length=10, verbose_name='Kuruluş Tarihi')),
                ('founder_name', models.CharField(blank=True, default='İFİ Yazılım Kurucuları', max_length=200, verbose_name='Kurucu Adı')),
                ('number_of_employees', models.CharField(blank=True, default='5-10', max_length=50, verbose_name='Çalışan Sayısı')),
                ('service_radius', models.CharField(blank=True, default='100000', max_length=20, verbose_name='Hizmet Yarıçapı (metre)')),
                ('average_rating', models.CharField(blank=True, default='4.8', max_length=10, verbose_name='Ortalama Puan')),
                ('review_count', models.CharField(blank=True, default='25', max_length=10, verbose_name='Yorum Sayısı')),
                ('contact_type', models.CharField(blank=True, default='customer service', max_length=50, verbose_name='İletişim Türü')),
                ('price_currency', models.CharField(blank=True, default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('country_name', models.CharField(blank=True, default='Turkey', max_length=50, verbose_name='Ülke Adı')),
                ('city_name', models.CharField(blank=True, default='İstanbul', max_length=50, verbose_name='Şehir Adı')),
                ('head_scripts', models.TextField(blank=True, help_text='<head> etiketi içine eklenecek kodlar (Google Analytics, Meta Pixel vb.)', verbose_name='Head Kodları')),
                ('body_scripts', models.TextField(blank=True, help_text='<body> etiketinin sonuna eklenecek kodlar', verbose_name='Body Kodları')),
                ('enable_sitemap', models.BooleanField(default=True, help_text='Otomatik sitemap.xml oluşturmayı aktifleştir', verbose_name='Sitemap Aktif')),
                ('enable_robots_txt', models.BooleanField(default=True, help_text='Otomatik robots.txt oluşturmayı aktifleştir', verbose_name='Robots.txt Aktif')),
                ('enable_structured_data', models.BooleanField(default=True, help_text='Schema.org yapılandırılmış verilerini aktifleştir', verbose_name='Structured Data Aktif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ayar',
                'verbose_name_plural': 'Genel Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Ana Başlık')),
                ('subtitle', models.CharField(default='', max_length=250, verbose_name='Alt Başlık')),
                ('description', models.TextField(default='', verbose_name='Açıklama')),
                ('primary_button_text', models.CharField(blank=True, max_length=100, verbose_name='Birincil Buton Yazısı')),
                ('primary_button_link', models.URLField(blank=True, verbose_name='Birincil Buton Linki')),
                ('primary_button_icon', models.CharField(blank=True, help_text='FontAwesome ikon adı (örn: fas fa-rocket)', max_length=50, verbose_name='Birincil Buton İkonu')),
                ('secondary_button_text', models.CharField(blank=True, max_length=100, verbose_name='İkincil Buton Yazısı')),
                ('secondary_button_link', models.URLField(blank=True, verbose_name='İkincil Buton Linki')),
                ('secondary_button_icon', models.CharField(blank=True, help_text='FontAwesome ikon adı (örn: fas fa-play)', max_length=50, verbose_name='İkincil Buton İkonu')),
                ('banner', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='uploads/Hero', verbose_name='Hero Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('counters', models.ManyToManyField(related_name='hero_counters', to='core.counter', verbose_name='Sayaçlar')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Herolar',
            },
        ),
        migrations.CreateModel(
            name='FeatureArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Üst Başlık')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('features', models.ManyToManyField(to='core.feature', verbose_name='Özellikler')),
            ],
            options={
                'verbose_name': 'Neden Bizi Seçmelisiniz',
                'verbose_name_plural': 'Neden Bizi Seçmelisiniz',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slogan')),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='Açıklama')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('mission', models.TextField(verbose_name='Misyon')),
                ('vision', models.TextField(verbose_name='Vizyon')),
                ('image', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='uploads/about', verbose_name='Hakkımızda Resim')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('counters', models.ManyToManyField(related_name='about_counters', to='core.counter', verbose_name='Sayaçlar')),
                ('features', models.ManyToManyField(to='core.feature', verbose_name='Özellikler')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
    ]
