# Generated by Django 4.2.17 on 2025-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_featurearea_image_featurearea_info_card_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurearea',
            name='highlighted_title',
            field=models.CharField(blank=True, help_text='Bu alan altın rengi ve gradient ile yazılacaktır.', max_length=100, null=True, verbose_name='Vurgulu Başlık (Gold)'),
        ),
        migrations.AlterField(
            model_name='featurearea',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık (Beyaz)'),
        ),
    ]
