# Generated by Django 4.2.17 on 2025-12-16 01:15

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurearea',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='Harita veya büyük görsel', null=True, upload_to='uploads/feature_area', verbose_name='Büyük Görsel'),
        ),
        migrations.AddField(
            model_name='featurearea',
            name='info_card_description',
            field=models.TextField(blank=True, default="İstanbul'un her noktasına ulaşabilen geniş araç filomuz ve uzman ekiplerimizle, tadilat süreçlerinizi aksatmadan yönetiyoruz.", verbose_name='Bilgi Kartı Açıklaması'),
        ),
        migrations.AddField(
            model_name='featurearea',
            name='info_card_icon',
            field=models.CharField(blank=True, default='fas fa-truck', help_text='FontAwesome ikon adı', max_length=50, verbose_name='Bilgi Kartı İkonu'),
        ),
        migrations.AddField(
            model_name='featurearea',
            name='info_card_title',
            field=models.CharField(blank=True, default='Mobil Ekiplerimiz', max_length=100, verbose_name='Bilgi Kartı Başlığı'),
        ),
    ]
