# Generated by Django 4.2.17 on 2025-12-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featurearea_image_featurearea_info_card_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurearea',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featurearea',
            name='info_card_description',
        ),
        migrations.RemoveField(
            model_name='featurearea',
            name='info_card_icon',
        ),
        migrations.RemoveField(
            model_name='featurearea',
            name='info_card_title',
        ),
    ]
