# Generated by Django 4.2.17 on 2025-12-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_after_image_service_before_image_servicestep'),
        ('core', '0005_featurearea_highlighted_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='service.service', verbose_name='İlgili Hizmet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='Örn: Mobilya Boyama', max_length=100, verbose_name='Kategori (Eski)'),
        ),
    ]
