# Generated by Django 4.2.17 on 2025-12-16 03:22

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_service_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_seo',
            name='hero_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='Eğer boş bırakılırsa varsayılan abstract gradient kullanılır.', null=True, upload_to='uploads/page_heroes', verbose_name='Hero Arka Plan Resmi'),
        ),
    ]
