# Generated by Django 4.2.17 on 2025-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_page_seo_hero_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page_Seo',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/about', verbose_name='Hakkımızda Resim'),
        ),
        migrations.AlterField(
            model_name='featurearea',
            name='image',
            field=models.ImageField(blank=True, help_text='Harita veya büyük görsel', null=True, upload_to='uploads/feature_area', verbose_name='Büyük Görsel'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='banner',
            field=models.ImageField(blank=True, upload_to='uploads/Hero', verbose_name='Hero Resmi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Sonrası Görseli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Öncesi Görseli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='uploads/projects', verbose_name='Ana Görsel'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logowhite',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Logo(Beyaz Yüzey)'),
        ),
    ]
