# Generated by Django 4.2.17 on 2025-12-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_page_seo_alter_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık'),
        ),
    ]
