# Generated by Django 4.2.17 on 2025-12-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_seo_description_project_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_comparison_hero',
            field=models.BooleanField(default=False, help_text='Bu proje anasayfadaki "Değişime Tanık Olun" bölümünde gösterilir. Sadece 1 proje seçilebilir.', verbose_name='Anasayfa Dönüşüm Alanı'),
        ),
    ]
