# Generated by Django 4.2.17 on 2025-12-17 01:24

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Kategori')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Etiket')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='Açıklama')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('image', models.ImageField(default='uploads/blog.jpg', upload_to='uploads/blogs', verbose_name='Resim')),
                ('miniimage', models.ImageField(blank=True, default='uploads/blog.jpg', upload_to='uploads/blogs', verbose_name='Küçük Resim (Opsiyonel)')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('showIndex', models.BooleanField(default=True, verbose_name='Anasayfa da gösterilsin mi?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Kategori')),
                ('tags', models.ManyToManyField(blank=True, help_text='Birden fazla seçim yapmak için te "CTRL" veya "COMMAND" tuşuna basılı tutun.', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'ordering': ['-created'],
            },
        ),
    ]
