# Generated by Django 4.2.17 on 2025-12-16 02:37

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_featurearea_highlighted_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome ikon adı (örn: fas fa-paint-brush)', max_length=50, verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hizmet Kategorisi',
                'verbose_name_plural': 'Hizmet Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='Açıklama')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hizmet Alanı',
                'verbose_name_plural': 'Hizmet Alanı',
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='Açıklama')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('image', image_optimizer.fields.OptimizedImageField(default='uploads/service_default.jpg', upload_to='uploads/services', verbose_name='Resim')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('showIndex', models.BooleanField(default=True, verbose_name='Anasayfa')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome ikon adı (örn: fas fa-info)', max_length=50, verbose_name='İcon')),
                ('faqs', models.ManyToManyField(blank=True, related_name='%(class)s_faqs', to='core.faq', verbose_name='Sıkça Sorulan Sorular')),
                ('features', models.ManyToManyField(blank=True, related_name='%(class)s_features', to='core.feature', verbose_name='Özellikler')),
            ],
            options={
                'verbose_name': 'Hizmet Bölgesi',
                'verbose_name_plural': 'Hizmet Bölgeleri',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='Açıklama')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('image', image_optimizer.fields.OptimizedImageField(default='uploads/service_default.jpg', upload_to='uploads/services', verbose_name='Resim')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('showIndex', models.BooleanField(default=True, verbose_name='Anasayfa')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome ikon adı (örn: fas fa-info)', max_length=50, verbose_name='İcon')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service.servicecategory', verbose_name='Kategori')),
                ('faqs', models.ManyToManyField(blank=True, related_name='%(class)s_faqs', to='core.faq', verbose_name='Sıkça Sorulan Sorular')),
                ('features', models.ManyToManyField(blank=True, related_name='%(class)s_features', to='core.feature', verbose_name='Özellikler')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['-created'],
            },
        ),
    ]
