# Generated by Django 4.2.17 on 2025-12-16 02:38

from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='after_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='uploads/services/transformations', verbose_name='Sonrası Resim (Dönüşüm)'),
        ),
        migrations.AddField(
            model_name='service',
            name='before_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='uploads/services/transformations', verbose_name='Öncesi Resim (Dönüşüm)'),
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='Adım No')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='service.service', verbose_name='Hizmet')),
            ],
            options={
                'verbose_name': 'Süreç Adımı',
                'verbose_name_plural': 'Süreç Adımları',
                'ordering': ['step_number'],
            },
        ),
    ]
