# Generated by Django 4.2.17 on 2025-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_after_image_service_before_image_servicestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/services/transformations', verbose_name='Sonrası Resim (Dönüşüm)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/services/transformations', verbose_name='Öncesi Resim (Dönüşüm)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='uploads/service_default.jpg', upload_to='uploads/services', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='image',
            field=models.ImageField(default='uploads/service_default.jpg', upload_to='uploads/services', verbose_name='Resim'),
        ),
    ]
