"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
try:
    from decouple import config, Csv
except Exception:
    import os
    def config(key, default=None, cast=None):
        value = os.getenv(key, default)
        if cast is None:
            return value
        try:
            return cast(value)
        except Exception:
            return value
    def Csv():
        return lambda v: [item.strip() for item in (v or '').split(',') if item.strip()]
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1_pyvzzlhkw%#b8^(j(jg%!ggbzd&7tfg^#)k-0x1*o!_cak#2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# CSRF Trusted Origins for production
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django_summernote',
    'image_optimizer',
    'core.apps.CoreConfig',
    'blog.apps.BlogConfig',
    'service.apps.ServiceConfig',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Session settings


ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.main',
                'core.context_processors.site_settings',  # Our custom context processor

            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use environment variable to determine database type
DATABASE_ENGINE = config('DATABASE_ENGINE', default='sqlite3')

if DATABASE_ENGINE == 'mysql':
    # Ensure PyMySQL works as MySQLdb if mysqlclient isn't installed
    try:
        import pymysql
        pymysql.install_as_MySQLdb()
    except Exception:
        pass
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME', default='ifiyazilim'),
            'USER': config('DB_USER', default='root'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    # Default to SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
X_FRAME_OPTIONS = 'SAMEORIGIN'

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Image Optimization Settings
IMAGE_OPTIMIZER = {
    'jpeg': {
        'quality': 85,
        'progressive': True,
        'optimize': True,
    },
    'png': {
        'optimize': True,
    },
    'webp': {
        'quality': 85,
        'lossless': False,
    },
}

# LCP Optimization Settings
LCP_OPTIMIZATION = {
    'hero_image_preload': True,
    'critical_css_inline': True,
    'font_preload': True,
    'resource_hints': True,
    'webp_support': True,
}

# Server Response Time Optimization
MIDDLEWARE.insert(0, 'django.middleware.gzip.GZipMiddleware')

# Static Files Storage
# ManifestStaticFilesStorage can cause issues with missing files in manifest
# Using standard storage to avoid "Missing staticfiles manifest entry" errors
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Database Query Optimization (SQLite compatible)
# SQLite doesn't need additional OPTIONS

# Static Files Compression
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# FID Optimization Settings
FID_OPTIMIZATION = {
    'ENABLE_WEB_WORKERS': True,
    'DEFER_NON_CRITICAL_JS': True,
    'USE_PASSIVE_LISTENERS': True,
    'LAZY_LOAD_JQUERY': True,
    'MONITOR_FID': True,
    'TARGET_FID_MS': 100,  # Target FID in milliseconds
}

# CLS Optimization Settings
CLS_OPTIMIZATION = {
    'ENABLE_IMAGE_DIMENSIONS': True,
    'ENABLE_FONT_OPTIMIZATION': True,
    'ENABLE_PLACEHOLDERS': True,
    'ENABLE_SKELETON_LOADING': True,
    'MONITOR_CLS': True,
    'TARGET_CLS_SCORE': 0.1,  # Target CLS score
    'IMAGE_MIN_HEIGHT': 200,  # Minimum height for images without dimensions
}

# Google Analytics 4 Settings
GOOGLE_ANALYTICS = {
    'GA4_MEASUREMENT_ID': os.getenv('GA4_MEASUREMENT_ID', 'G-XXXXXXXXXX'),  # Replace with your GA4 ID
    'ENABLE_ANALYTICS': os.getenv('ENABLE_ANALYTICS', 'True').lower() == 'true',
    'ENABLE_DEBUG_MODE': DEBUG,  # Debug mode in development
    'ENABLE_EVENTS': True,
    'ENABLE_CONVERSIONS': True,
    'ENABLE_CORE_WEB_VITALS': True,
}

# Google Search Console Settings
GOOGLE_SEARCH_CONSOLE = {
    'SITE_VERIFICATION_CODE': os.getenv('GSC_VERIFICATION_CODE', ''),  # HTML meta tag verification code
    'ENABLE_SITEMAP': True,
    'ENABLE_ROBOTS_TXT': True,
    'ENABLE_STRUCTURED_DATA': True,
    'ENABLE_CORE_WEB_VITALS': True,
    'SITEMAP_URLS': [
        '/sitemap.xml',
        '/sitemap-services.xml',
        '/sitemap-blogs.xml',
    ],
}

# Google Tag Manager Settings
GOOGLE_TAG_MANAGER = {
    'GTM_CONTAINER_ID': os.getenv('GTM_CONTAINER_ID', 'GTM-XXXXXXX'),  # Replace with your GTM Container ID
    'ENABLE_GTM': os.getenv('ENABLE_GTM', 'True').lower() == 'true',
    'ENABLE_DEBUG_MODE': DEBUG,  # Debug mode in development
    'ENABLE_DATA_LAYER': True,
    'ENABLE_CUSTOM_EVENTS': True,
    'ENABLE_E_COMMERCE': True,
    'ENABLE_CROSS_DOMAIN': False,
}

# Compression Settings
COMPRESS_ENABLED = True
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.rJSMinFilter',
]

# Cache Settings for Static Files
STATICFILES_CACHE_TIMEOUT = 31536000  # 1 year

# Media Files Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Image Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
       
    },
}

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')

# Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    
    # Respect HTTPS when behind a proxy/CDN
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Session Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

# Cache Configuration
# Use Redis in production, local memory in development
CACHE_BACKEND = config('CACHE_BACKEND', default='locmem')

if CACHE_BACKEND == 'redis':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
            'TIMEOUT': 300,
        }
    }
else:
    # Default to local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
